name: Run CAPTCHA Solver

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Run CAPTCHA Solver
      run: node runCaptchaSolver.js

    - name: Upload screenshot
      uses: actions/upload-artifact@v2
      with:
        name: screenshot
        path: screenshot.png